version: '3.1'

services:
  db:
    image: postgres:13.2
    restart: unless-stopped
    volumes:
      - linear-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: linear_dev
    ports:
      - 5432:5432
volumes:
    linear-db: